### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by colonelpanic8**

### CODE REVIEW

**Comment by colonelpanic8** [comment]
@alternateved did that work?

**Comment by alternateved** [comment]
I'll let you know as soon as it rebuilds and reboots. But nevertheless, thank you very much for taking the time and checking my configuration.

**Comment by colonelpanic8** [comment]
@alternateved can you verify that a binary alternateved_64-linux is there? That should be you actual xmonad binary.

**Comment by alternateved** [comment]
Binary alternateved-xmonad is there, it was the one active. I've checked processes and it was the one spawned by lightdm. It is also in the path. Also, latest xmonad-contrib modules are imported. I was able to recompile xmonad (during nixos rebuild) with those modules.

**Pull request merged**
